Update parent project and deploy scripts

diff --git a/src/main/tools/travis/prepare_release b/src/main/tools/travis/prepare_release
--- a/src/main/tools/travis/prepare_release
+++ b/src/main/tools/travis/prepare_release
@@ -10,10 +10,18 @@ commit_snapshot () {
   git push
 }
 
+if [ -z "$1" ]; then
+  echo "Please supply a version increment argument: major, minor, or patch"
+  echo "  e.g., src/main/tools/travis/prepare_release patch"
+  exit 1
+fi
+
 echo "Preparing $($DIR/get_version)"
 
 $DIR/version
 $DIR/clean
+
+mvn -q clean install
 
 git commit -am "Creating new version: $($DIR/get_version)"
 git push
@@ -21,16 +29,17 @@ git push
 $DIR/tag "$TAG"
 $DIR/push_tag
 
-if [ "$1" == 'M' ]; then
-  $DIR/set_version "$($DIR/increment_version -M $($DIR/get_version))"
+if [ "$1" == 'major' ]; then
+  $DIR/set_version "$($DIR/increment_version -M $($DIR/get_version))-SNAPSHOT"
   commit_snapshot
-elif [ "$1" == 'm' ]; then
-  $DIR/set_version "$($DIR/increment_version -m $($DIR/get_version))"
+elif [ "$1" == 'minor' ]; then
+  $DIR/set_version "$($DIR/increment_version -m $($DIR/get_version))-SNAPSHOT"
   commit_snapshot
-elif [ "$1" == 'p' ]; then
-  $DIR/set_version "$($DIR/increment_version -p $($DIR/get_version))"
+elif [ "$1" == 'patch' ]; then
+  $DIR/set_version "$($DIR/increment_version -p $($DIR/get_version))-SNAPSHOT"
   commit_snapshot
 else
-  echo "No version increment arg give so you must manually increment"
+  echo "Error: unrecognized version increment argument"
+  echo "  Please run this script with major, minor, or patch"
 fi
 
